	PRINTV	__RANDSEED
	PRINTT	"\n"
	PRINTV	rand(1,4)
	PRINTV	rand(0,15)
	PRINTV	rand(87,100)
	PRINTT	"\n"
	PRINTV	__RANDSEED
	PRINTT	"\n"

	RANDSEED $DEADF00D
	PRINTV	__RANDSEED
	PRINTT	"\n"
	PRINTV	rand(1,4)
	PRINTV	rand(0,15)
	PRINTV	rand(87,100)
	PRINTT	"\n"

rand	EQU	2

	PRINTV	rand
	PRINTT	"\n"